server:
  port: 8080

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.config: INFO
